#!/bin/bash

#######################

# author: anil
# version: v1

# this script will report the aws resource usage 

######################

set -x



# AWS EC2
# AWS S3
# AWS IAM users
# AWS LAMBDA

# list s3 buckets

echo "print s3 buckets"
aws s3 ls

# list ec2 instances

echo "ec2 instances"
#aws ec2 describe-instances
aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'
# list lambda

echo "aws lambda"
aws lambda list-functions


# list IAM users

echo"print iam users"
aws iam list-users



